development:
  clients:
    default:
      database: cointegracao
      hosts:
        - ds119618.mlab.com:19618
      options:
        user: 'new_read'
        password: '123456'

test:
  clients:
    default:
      database: cointegracao_test
      hosts:
        - db:27017
      user: 'root'
      password: 'root'
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      database: cointegracao
      hosts:
        - ds119618.mlab.com:19618
      options:
        user: 'new_read'
        password: '123456'
